//-----libs-begin-----
loadLib("libs/laya.core.js")
loadLib("libs/laya.ani.js")
loadLib("libs/laya.html.js")
loadLib("libs/laya.particle.js")
loadLib("libs/laya.ui.js")
loadLib("libs/laya.device.js")
//-----libs-end-------
loadLib("js/bundle.js")